#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/.dotfiles/nvim/.config ~/projects ~/ ~/work ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)


if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    tmux new-window -t $selected_name -c $selected
    tmux rename-window -t $selected_name:0 nvim
    tmux rename-window -t $selected_name:1 term
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    tmux new-window -t $selected_name -c $selected
    tmux rename-window -t $selected_name:0 nvim
    tmux rename-window -t $selected_name:1 term
fi

tmux switch-client -t $selected_name
